// @ts-check

const chains = [
  {
    id: "arbitrumOneApi",
    type: "autogenerated",
    dirName: "arbitrum-one-api",
    label: "Arbitrum One",
    link: "/arbitrum-one-api/intro",
  },
  {
    id: "avalancheApi",
    type: "autogenerated",
    dirName: "avalanche-api",
    label: "Avalanche",
    link: "/avalanche-api/intro",
  },
  {
    id: "baseApi",
    type: "autogenerated",
    dirName: "base-api",
    label: "Base",
    link: "/base-api/intro",
  },
  {
    id: "binanceSmartChainApi",
    type: "autogenerated",
    dirName: "binance-smart-chain-api",
    label: "Binance Smart Chain",
    link: "/binance-smart-chain-api/intro",
  },
  {
    id: "bobaApi",
    type: "autogenerated",
    dirName: "boba-api",
    label: "Boba",
    link: "/boba-api/intro",
  },
  {
    id: "celestiaApi",
    type: "autogenerated",
    dirName: "celestia-api",
    label: "Celestia",
    link: "/celestia-api/intro",
  },
  {
    id: "celoApi",
    type: "autogenerated",
    dirName: "celo-api",
    label: "Celo",
    link: "/celo-api/intro",
  },
  {
    id: "ethereumApi",
    type: "autogenerated",
    dirName: "ethereum-api",
    label: "Ethereum",
    link: "/ethereum-api/intro",
  },
  {
    id: "evmosApi",
    type: "autogenerated",
    dirName: "evmos-api",
    label: "Evmos",
    link: "/evmos-api/intro",
  },
  {
    id: "fantomApi",
    type: "autogenerated",
    dirName: "fantom-api",
    label: "Fantom",
    link: "/fantom-api/intro",
  },
  {
    id: "fuseApi",
    type: "autogenerated",
    dirName: "fuse-api",
    label: "Fuse",
    link: "/fuse-api/intro",
  },
  {
    id: "gnosisApi",
    type: "autogenerated",
    dirName: "gnosis-api",
    label: "Gnosis Chain",
    link: "/gnosis-api/intro",
  },
  {
    id: "harmonyShard0Api",
    type: "autogenerated",
    dirName: "harmony-shard-0-api",
    label: "Harmony Shard 0",
    link: "/harmony-shard-0-api/intro",
  },
  {
    id: "iotexApi",
    type: "autogenerated",
    dirName: "iotex-api",
    label: "IoTeX",
    link: "/iotex-api/intro",
  },
  {
    id: "kavaApi",
    type: "autogenerated",
    dirName: "kava-api",
    label: "Kava",
    link: "/kava-api/intro",
  },
  {
    id: "klaytnApi",
    type: "autogenerated",
    dirName: "klaytn-api",
    label: "Klaytn",
    link: "/klaytn-api/intro",
  },
  {
    id: "metisApi",
    type: "autogenerated",
    dirName: "metis-api",
    label: "Metis",
    link: "/metis-api/intro",
  },
  {
    id: "moonbeamApi",
    type: "autogenerated",
    dirName: "moonbeam-api",
    label: "Moonbeam",
    link: "/moonbeam-api/intro",
  },
  {
    id: "moonriverApi",
    type: "autogenerated",
    dirName: "moonriver-api",
    label: "Moonriver",
    link: "/moonriver-api/intro",
  },
  {
    id: "nearApi",
    type: "autogenerated",
    dirName: "near-api",
    label: "Near",
    link: "/near-api/intro",
  },
  {
    id: "oasysApi",
    type: "autogenerated",
    dirName: "oasys-api",
    label: "Oasys",
    link: "/oasys-api/intro",
  },
  {
    id: "okcApi",
    type: "autogenerated",
    dirName: "okc-api",
    label: "OKC",
    link: "/okc-api/intro",
  },
  {
    id: "optimismApi",
    type: "autogenerated",
    dirName: "optimism-api",
    label: "Optimism",
    link: "/optimism-api/intro",
  },
  {
    id: "osmosisApi",
    type: "autogenerated",
    dirName: "osmosis-api",
    label: "Osmosis",
    link: "/osmosis-api/intro",
  },
  {
    id: "poktApi",
    type: "autogenerated",
    dirName: "pokt-api",
    label: "Pokt Network",
    link: "/pokt-api/intro",
  },
  {
    id: "polygonApi",
    type: "autogenerated",
    dirName: "polygon-api",
    label: "Polygon",
    link: "/polygon-api/intro",
  },
  {
    id: "radixApi",
    type: "autogenerated",
    dirName: "radix-api",
    label: "Radix",
    link: "/radix-api/intro",
  },
  {
    id: "scrollApi",
    type: "autogenerated",
    dirName: "scroll-api",
    label: "Scroll",
    link: "/scroll-api/intro",
  },
  {
    id: "solanaApi",
    type: "autogenerated",
    dirName: "solana-api",
    label: "Solana",
    link: "/solana-api/intro",
  },
  {
    id: "suiApi",
    type: "autogenerated",
    dirName: "sui-api",
    label: "Sui",
    link: "/sui-api/intro",
  },
]

const chainsSupportedItems = chains.map((chain) => ({
  type: "link",
  label: chain.label,
  href: chain.link,
}))

const chainsSidebars = chains.reduce((prev, curr) => {
  return {
    ...prev,
    [curr.id]: [
      {
        type: curr.type,
        dirName: curr.dirName,
        customProps: {
          label: curr.label,
          link: curr.link,
        },
      },
    ],
  }
}, {})

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
let sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guides: [
    {
      type: "autogenerated",
      dirName: "guides",
      customProps: {
        label: "Guides",
        link: "/guides/getting-started/welcome-to-grove",
      },
    },
  ],
  groveApi: [
    {
      type: "autogenerated",
      dirName: "grove-api",
      customProps: {
        label: "Grove API",
        link: "/grove-api/getting-started/introduction",
      },
    },
    {
      type: "category",
      label: "Supported Chains",
      collapsible: false,
      items: chainsSupportedItems,
    },
  ],
  ...chainsSidebars,
}

module.exports = sidebars
