// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
let sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guides: [
    {
      type: "autogenerated",
      dirName: "guides",
      customProps: {
        label: "Guides",
        link: "/guides/getting-started/welcome-to-grove",
      },
    },
  ],
  groveApi: [
    {
      type: "autogenerated",
      dirName: "grove-api",
      customProps: {
        label: "Grove API",
        link: "/grove-api/getting-started/introduction",
      },
    },
    {
      type: "category",
      label: "Supported Chains",
      collapsible: false,
      items: [
        {
          type: "link",
          label: "Arbitrum One API",
          href: "/arbitrum-one-api/intro",
        },
        {
          type: "link",
          label: "Avalanche API",
          href: "/avalanche-api/intro",
        },
        {
          type: "link",
          label: "Binance Smart Chain API",
          href: "/binance-smart-chain-api/intro",
        },
        {
          type: "link",
          label: "Ethereum API",
          href: "/ethereum-api/intro",
        },
        {
          type: "link",
          label: "Polygon API",
          href: "/polygon-api/intro",
        },
      ],
    },
  ],
  arbitrumOneApi: [
    {
      type: "autogenerated",
      dirName: "arbitrum-one-api",
      customProps: {
        label: "Arbitrum One API",
        link: "/arbitrum-one-api/intro",
      },
    },
  ],
  avalancheApi: [
    {
      type: "autogenerated",
      dirName: "avalanche-api",
      customProps: {
        label: "Avalanche API",
        link: "/avalanche-api/intro",
      },
    },
  ],
  baseApi: [
    {
      type: "autogenerated",
      dirName: "base-api",
      customProps: {
        label: "Base API",
        link: "/base-api/intro",
      },
    },
  ],
  binanceSmartChainApi: [
    {
      type: "autogenerated",
      dirName: "binance-smart-chain-api",
      customProps: {
        label: "Binance Smart Chain API",
        link: "/binance-smart-chain-api/intro",
      },
    },
  ],
  bobaApi: [
    {
      type: "autogenerated",
      dirName: "boba-api",
      customProps: {
        label: "Boba API",
        link: "/boba-api/intro",
      },
    },
  ],
  celoApi: [
    {
      type: "autogenerated",
      dirName: "celo-api",
      customProps: {
        label: "Celo API",
        link: "/celo-api/intro",
      },
    },
  ],
  dogechainApi: [
    {
      type: "autogenerated",
      dirName: "dogechain-api",
      customProps: {
        label: "Dogechain API",
        link: "/dogechain-api/intro",
      },
    },
  ],
  ethereumApi: [
    {
      type: "autogenerated",
      dirName: "ethereum-api",
      customProps: {
        label: "Ethereum API",
        link: "/ethereum-api/intro",
      },
    },
  ],
  evmosApi: [
    {
      type: "autogenerated",
      dirName: "evmos-api",
      customProps: {
        label: "Evmos API",
        link: "/evmos-api/intro",
      },
    },
  ],
  fantomApi: [
    {
      type: "autogenerated",
      dirName: "fantom-api",
      customProps: {
        label: "Fantom API",
        link: "/fantom-api/intro",
      },
    },
  ],
  fuseApi: [
    {
      type: "autogenerated",
      dirName: "fuse-api",
      customProps: {
        label: "Fuse API",
        link: "/fuse-api/intro",
      },
    },
  ],
  polygonApi: [
    {
      type: "autogenerated",
      dirName: "polygon-api",
      customProps: {
        label: "Polygon API",
        link: "/polygon-api/intro",
      },
    },
  ],
}

module.exports = sidebars
