import React from "react"

export const supportedBlockchains = [
  {
    name: "Pocket Network",
    portalApiPrefix: "pocket",
    relayChainID: "F000",
    evmChainID: "",
    link: "/pocket-api/intro",
  },
  {
    name: "Arbitrum One",
    portalApiPrefix: "arb-one",
    relayChainID: "F001",
    evmChainID: "42161",
    link: "/arbitrum-one-api/intro",
  },
  {
    name: "Arbitrum Sepolia Testnet",
    portalApiPrefix: "arb-sepolia-testnet",
    relayChainID: "F002",
    evmChainID: "421614",
    link: "/arbitrum-one-api/intro",
  },
  {
    name: "Avalanche",
    portalApiPrefix: "avax",
    relayChainID: "F003",
    evmChainID: "43114",
    link: "/avalanche-api/intro",
  },
  {
    name: "DeFi Kingdoms",
    portalApiPrefix: "avax-dfk",
    relayChainID: "F004",
    evmChainID: "53935",
    link: "/avalanche-api/intro",
  },
  {
    name: "Base",
    portalApiPrefix: "base",
    relayChainID: "F005",
    evmChainID: "8453",
    link: "/base-api/intro",
  },
  {
    name: "Base Sepolia Testnet",
    portalApiPrefix: "base-sepolia-testnet",
    relayChainID: "F006",
    evmChainID: "84532",
    link: "/base-api/intro",
  },
  {
    name: "Berachain",
    portalApiPrefix: "bera",
    relayChainID: "F031",
    evmChainID: "80084",
    link: "/berachain-api/intro",
  },
  {
    name: "Blast",
    portalApiPrefix: "blast",
    relayChainID: "F008",
    evmChainID: "238",
    link: "/blast-api/intro",
  },
  {
    name: "BNB Smart Chain",
    portalApiPrefix: "bsc",
    relayChainID: "F009",
    evmChainID: "56",
    link: "/binance-smart-chain-api/intro",
  },
  {
    name: "Boba",
    portalApiPrefix: "boba",
    relayChainID: "F00A",
    evmChainID: "288",
    link: "/boba-api/intro",
  },
  {
    name: "Celo",
    portalApiPrefix: "celo",
    relayChainID: "F00B",
    evmChainID: "42220",
    link: "/celo-api/intro",
  },
  {
    name: "Ethereum",
    portalApiPrefix: "eth",
    relayChainID: "F00C",
    evmChainID: "0001",
    link: "/ethereum-api/intro",
  },
  {
    name: "Ethereum Holesky Testnet",
    portalApiPrefix: "eth-holesky-testnet",
    relayChainID: "F00D",
    evmChainID: "17000",
    link: "/ethereum-api/intro",
  },
  {
    name: "Ethereum Sepolia Testnet",
    portalApiPrefix: "eth-sepolia-testnet",
    relayChainID: "F00E",
    evmChainID: "11155111",
    link: "/ethereum-api/intro",
  },
  {
    name: "Evmos",
    portalApiPrefix: "evmos",
    relayChainID: "F00F",
    evmChainID: "9001",
    link: "/evmos-api/intro",
  },
  {
    name: "Fantom",
    portalApiPrefix: "fantom",
    relayChainID: "F010",
    evmChainID: "250",
    link: "/fantom-api/intro",
  },
  {
    name: "Fraxtal",
    portalApiPrefix: "fraxtal",
    relayChainID: "F011",
    evmChainID: "250",
    link: "/fraxtal-api/intro",
  },
  {
    name: "Fuse",
    portalApiPrefix: "fuse",
    relayChainID: "F012",
    evmChainID: "122",
    link: "/fuse-api/intro",
  },
  {
    name: "Gnosis",
    portalApiPrefix: "gnosis",
    relayChainID: "F013",
    evmChainID: "100",
    link: "/gnosis-api/intro",
  },
  {
    name: "Harmony Shard 0",
    portalApiPrefix: "harmony",
    relayChainID: "F014",
    evmChainID: "1666600000",
    link: "/harmony-shard-0-api/intro",
  },
  {
    name: "Ink",
    portalApiPrefix: "ink",
    relayChainID: "F032",
    evmChainID: "57073",
    link: "/ink-api/intro",
  },
  {
    name: "IoTeX",
    portalApiPrefix: "iotex",
    relayChainID: "F015",
    evmChainID: "4689",
    link: "/iotex-api/intro",
  },
  {
    name: "Kaia",
    portalApiPrefix: "kaia",
    relayChainID: "F016",
    evmChainID: "8217",
    link: "/kaia-api/intro",
  },
  {
    name: "Kava",
    portalApiPrefix: "kava",
    relayChainID: "F017",
    evmChainID: "2222",
    link: "/kava-api/intro",
  },
  {
    name: "Linea",
    portalApiPrefix: "linea",
    relayChainID: "F030",
    evmChainID: "59144",
    link: "/linea-api/intro",
  },
  {
    name: "Mantle",
    portalApiPrefix: "mantle",
    relayChainID: "F033",
    evmChainID: "5000",
    link: "/mantle-api/intro",
  },
  {
    name: "Metis",
    portalApiPrefix: "metis",
    relayChainID: "F018",
    evmChainID: "1088",
    link: "/metis-api/intro",
  },
  {
    name: "Moonbeam",
    portalApiPrefix: "moonbeam",
    relayChainID: "F019",
    evmChainID: "1284",
    link: "/moonbeam-api/intro",
  },
  {
    name: "Moonriver",
    portalApiPrefix: "moonriver",
    relayChainID: "F01A",
    evmChainID: "1285",
    link: "/moonriver-api/intro",
  },
  {
    name: "NEAR",
    portalApiPrefix: "near",
    relayChainID: "F01B",
    evmChainID: "",
    link: "/near-api/intro",
  },
  {
    name: "Oasys",
    portalApiPrefix: "oasys",
    relayChainID: "F01C",
    evmChainID: "248",
    link: "/oasys-api/intro",
  },
  {
    name: "Optimism",
    portalApiPrefix: "op",
    relayChainID: "F01D",
    evmChainID: "10",
    link: "/optimism-api/intro",
  },
  {
    name: "Optimism Sepolia Testnet",
    portalApiPrefix: "op-sepolia-testnet",
    relayChainID: "F01E",
    evmChainID: "11155420",
    link: "/optimism-api/intro",
  },
  {
    name: "opBNB",
    portalApiPrefix: "opbnb",
    relayChainID: "F01F",
    evmChainID: "204",
    link: "/opbnb-api/intro",
  },
  {
    name: "Osmosis",
    portalApiPrefix: "osmosis",
    relayChainID: "F020",
    evmChainID: "",
    link: "/osmosis-api/intro",
  },
  {
    name: "Polygon",
    portalApiPrefix: "poly",
    relayChainID: "F021",
    evmChainID: "137",
    link: "/polygon-api/intro",
  },
  {
    name: "Polygon Amoy Testnet",
    portalApiPrefix: "poly-amoy-testnet",
    relayChainID: "F022",
    evmChainID: "80002",
    link: "/polygon-api/intro",
  },
  {
    name: "Polygon zkEVM",
    portalApiPrefix: "poly-zkevm",
    relayChainID: "F029",
    evmChainID: "1101",
    link: "/polygon-api/intro",
  },
  {
    name: "Radix",
    portalApiPrefix: "radix",
    relayChainID: "F023",
    evmChainID: "",
    link: "/radix-api/intro",
  },
  {
    name: "Scroll",
    portalApiPrefix: "scroll",
    relayChainID: "F024",
    evmChainID: "534352",
    link: "/scroll-api/intro",
  },
  {
    name: "Sei",
    portalApiPrefix: "sei",
    relayChainID: "F034",
    evmChainID: "1329",
    link: "/sei-api/intro",
  },
  {
    name: "Sonic",
    portalApiPrefix: "sonic",
    relayChainID: "F02D",
    evmChainID: "146",
    link: "/sonic-api/intro",
  },
  {
    name: "Solana",
    portalApiPrefix: "solana",
    relayChainID: "F025",
    evmChainID: "",
    link: "/solana-api/intro",
  },
  {
    name: "Sui",
    portalApiPrefix: "sui",
    relayChainID: "F026",
    evmChainID: "",
    link: "/sui-api/intro",
  },
  {
    name: "Taiko",
    portalApiPrefix: "taiko",
    relayChainID: "F027",
    evmChainID: "167000",
    link: "/taiko-api/intro",
  },
  {
    name: "Taiko Hekla Testnet",
    portalApiPrefix: "taiko-hekla-testnet",
    relayChainID: "F028",
    evmChainID: "167009",
    link: "/taiko-api/intro",
  },
  {
    name: "TRON",
    portalApiPrefix: "tron",
    relayChainID: "F02E",
    evmChainID: "728126428",
    link: "/tron-api/intro",
  },
  {
    name: "zkLink Nova",
    portalApiPrefix: "zklink-nova",
    relayChainID: "F02A",
    evmChainID: "810180",
    link: "/zklink-nova-api/intro",
  },
  {
    name: "zkSync Era",
    portalApiPrefix: "zksync-era",
    relayChainID: "F02B",
    evmChainID: "324",
    link: "/zksync-era-api/intro",
  },
]

// ----------------------------------------------------------------------------
// DataTable column definition
// ----------------------------------------------------------------------------
export const columns = [
  {
    Header: "Service Name",
    accessor: "name",
    className: "pokt-data-table header left",
  },
  {
    Header: "Service ID",
    accessor: "portalApiPrefix",
    className: "pokt-data-table header left",
  },
  {
    Header: "Service ID",
    accessor: "relayChainID",
    className: "pokt-data-table header left"
  }
]
